### ISSUE TITLE
PDFtronwebviewer gets stuck at Loading Icon while loading Blob Content

### ISSUE THREAD

**Issue by hansaliyad1** [PDFTron/webviewer-salesforce#10]
Hey!

I hope you are doing well. I am trying to open up File content in Blob format and pdftronwebviewer gets stuck at loading icon. I have an Apex class which gets PDF file from Azure Blob storage via HTTPS GET request. The response body of HTTPS GET request has a raw PDF file content. I convert that content to Blob and encode as Base64 and returns the Base64 content as a string from Apex class to LWC JavaScript function. 

```
public Boolean getBlob(String sharedKey)
    {
        HttpRequest req = new HttpRequest();

        req.setMethod('GET');

        req.setHeader('x-ms-date', formattedDate);
        req.setHeader('Authorization', sharedKey);

        req.setEndpoint(this.requestURL);

        Http http = new Http();
        HTTPResponse res = http.send(req);
        // in the response body you have your blob
        System.debug('Status--->'+res.getStatus());
        System.debug('Status Code--->'+res.getStatusCode());
        if(res.getStatusCode() == 200) {
            this.strFileBody = res.getBody();
            this.blobFileBody = Blob.valueof(strFileBody);
            this.base64FileBody = EncodingUtil.base64Encode(blobFileBody);
            return true;
        }
        return false;
    }
```

In LWC JavaScript, I have the function base64ToBlob, which converts base64 content back to blob. I then fire an event with the blob that runs the case "OPEN_DOCUMENT_BLOB" which loads the blob. I did make sure the case was getting blob content. The pdftronwebviewer displays a loading icon and then nothing happens. I am not sure what am I missing.

```
\** Calling Apex Function **\
getFileFromAzure({ documentID: this.recordId })
                .then(response => {
                    console.log(response);
                    const res = JSON.parse(response);
                    console.log(this.base64ToBlob(res.base64FileBody));
                    fireEvent(this.pageRef, 'blobSelected', this.base64ToBlob(res.base64FileBody))
                })
                .catch(error => {
                    console.error(JSON.stringify(error));
                })
```

```
\** Converts base64 to Blob. **\
base64ToBlob(base64) {
        const binaryString = window.atob(base64);
        const len = binaryString.length;
        const bytes = new Uint8Array(len);
        for (let i = 0; i < len; ++i) {
            bytes[i] = binaryString.charCodeAt(i);
        }

        return new Blob([bytes], { type: 'application/pdf' });
    };
```

```
\** Case that opens up the Blob **\
case 'OPEN_DOCUMENT_BLOB':
        const { blob, extension, filename, documentId } = event.data.file;
        event.target.instance.loadDocument(blob, { extension, filename, documentId,
          officeOptions: {
            disableBrowserFontSubstitution: true,
          }
        })
        break;
```

I will appreciate if someone can provide their valuable inputs. Thank you!

**Comment by hansaliyad1** [comment]
Hey! I have figured this out. I was not providing `extension, filename, documentId` in below function. Once I provided that information, it was able to load the document.

```
\** Case that opens up the Blob **\
case 'OPEN_DOCUMENT_BLOB':
        const { blob, extension, filename, documentId } = event.data.file;
        event.target.instance.loadDocument(blob, { extension, filename, documentId,
          officeOptions: {
            disableBrowserFontSubstitution: true,
          }
        })
        break;
```

**Comment by tommywintersr** [comment]
@hansaliyad1 Great, glad to hear it is working now. 

Just a side note: 
You can also pass the link directly into your `loadDocument(fileURL, { extension, filename, documentId })` function. This way you do not need to call `EncodingUtil.base64encode()` in your Apex class, which can result in governor limits being exceeded for larger files (heap size memory is limited at 6MB for synchronous Apex).

**Comment by hansaliyad1** [comment]
@tommywintersr Thank you for the info. I do would like to talk to someone about Governor limits for this particular project. I think I should reach PDFtron or Salesforce regarding this. I understand not all of my questions can be answered by any one of them. Who would you recommend I should reach out to from PDFtron? Or should I just fill up contact us form on website? Thank you!

**Comment by tommywintersr** [comment]
Yes, you can fill out the form on our website and we can set up a call with you (you can specify that you would like a technical resource on the call to answer any questions in relation to Governor Limits).

**Comment by hansaliyad1** [comment]
Thank you! I will do that!

**Comment by hansaliyad1** [comment]
> @hansaliyad1 Great, glad to hear it is working now.
> 
> Just a side note: You can also pass the link directly into your `loadDocument(fileURL, { extension, filename, documentId })` function. This way you do not need to call `EncodingUtil.base64encode()` in your Apex class, which can result in governor limits being exceeded for larger files (heap size memory is limited at 6MB for synchronous Apex).

@tommywintersr I am aware I closed this issue but wanted to refer to one of your comment here. I am trying to implement this on Salesforce, but I am getting CORS error. Likewise, I am pulling this document from Azure. Is this telling me to configure CORS on Azure Storage Account?

```
Access to XMLHttpRequest at '' from origin '' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. 
```

**Comment by hansaliyad1** [comment]
@tommywintersr Never mind. I was able to figure this out. I had to add CORS policy in Azure Storage. Thank you!
