### ISSUE TITLE
Webviewer not coming up

### ISSUE THREAD

**Issue by hansaliyad1** [PDFTron/webviewer-salesforce#7]
I tried to install this in my scratch org and the webviewer is not coming up when I open PDFTron app. I checked the console and it shows the below error message.

```
ReferenceError: PDFTron is not defined
    at u.initUI (pdftronWebViewer.js:4)
    at eval (pdftronWebViewer.js:4)
```
Any suggestion what I am doing wrong? There were no errors during deployment.

**Comment by tommywintersr** [comment]
Hi @hansaliyad1, can you share your file tree structure in your /staticresources/ folder (only the relevant files related to WebViewer/PDFTron)? Thanks!

**Comment by hansaliyad1** [comment]
Sure! Here:

<img width="257" alt="image" src="https://user-images.githubusercontent.com/9779007/129243778-e9dd82ef-0e7d-4970-86e1-64b3903b3403.png">

**Comment by tommywintersr** [comment]
Thanks! If you are on version 8.x+, you need to change the constructor call from `new PDFTron.WebViewer()` to `new WebViewer()`. Will get this repo updated shortly as well.

Reference:
https://www.pdftron.com/documentation/web/get-started/migrating-to-v8/#apis-removed

**Comment by hansaliyad1** [comment]
That works!! Thank you so much!
