### ISSUE TITLE
Config.js: Cannot read property 'loadDocument' of undefined

### ISSUE THREAD

**Issue by hansaliyad1** [PDFTron/webviewer-salesforce#8]
When file is selected from "Choose a file to view" drop down menu, Config.js throws below error on line 41. It is a receiveMessage function on case "OPEN_DOCUMENT". 

```
Uncaught TypeError: Cannot read property 'loadDocument' of undefined
    at receiveMessage (config.js:41)
```

`event.data.file` variable do contains the file URL. 

What could I be doing wrong here? Thank you!

**Comment by tommywintersr** [comment]
Can you try changing `readerControl` to `instance`, ie. `instance.loadDocument(event.data.file)`

also if you are planning on using `readerControl.docViewer`, it has been moved to `instance.Core.documentViewer`.

Let me know if that helps - again thanks for your patience as we update this sample.

Thomas

**Comment by hansaliyad1** [comment]
Thank you again Thomas!! That works! You are awesome!
